version: '3.4'
services:
  mongodb1:
    image: mongo:5
    hostname: mongodb1
    container_name: mongodb1
    command: --port 25015  --bind_ip_all --replSet main 
    ports: 
      - '25015:25015'
    volumes: 
      - ../mongo/dat/primary:/data/db:rw
    networks:
      - wallet_internal
    restart: on-failure
  mongodb2:
    image: mongo:5
    container_name: mongodb2
    hostname: mongodb2
    command: --port 25016 --bind_ip_all --replSet main
    ports: 
      - '25016:25016'
    volumes:
      - ../mongo/dat/secondary:/data/db:rw
    networks:
      - wallet_internal
    restart: on-failure
  mongodb3:
    image: mongo:5
    container_name: mongodb3
    hostname: mongodb3
    command: --port 25017 --bind_ip_all --replSet main
    ports: 
      - '25017:25017'
    volumes:
      - ../mongo/dat/arbiter:/data/db:rw
    networks:
      - wallet_internal
    restart: on-failure
networks:
  wallet_internal:
    external: true
